// This file was automatically generated by lister-gen

package v1alpha2

// IdlerListerExpansion allows custom methods to be added to
// IdlerLister.
type IdlerListerExpansion interface{}

// IdlerNamespaceListerExpansion allows custom methods to be added to
// IdlerNamespaceLister.
type IdlerNamespaceListerExpansion interface{}
